# .github/workflows/deploy.yml
name: Deploy Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Deploy Application
        run: |
          
          echo "Deployment successful! Your application has been updated."
