name: Deploy to AWS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
     -  name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd fastapi-book-project
            git stash
            git pull origin main
            # Stop existing containers
            docker-compose down || true
            # Build and start containers
            docker-compose up --build -d
            # Verify containers are running
            docker ps
